app:
  # set value in environment variable
  MYSQL_USERNAME:
  MYSQL_PASSWORD:
  MYSQL_ADDRESS:
  MYSQL_DATABASE:
  ALIGO_API_KEY:
  ALIGO_ACCOUNT_ID:
  ALIGO_SENDER:
  JWT_KEY:
  CLOUD_MANAGEMENT_KEY:
  S3_REGION:
  AWS_S3_ID:
  AWS_S3_KEY:

auth:
  accessTokenDuration: "24h"
  parentProfileS3Bucket: "first-baby-time"
