version: '3.5'
services:
  server:
    image: mspring03/first-baby-time:${VERSION}.RELEASE
    container_name: server
    ports:
    - target: 80
      published: 8000
      protocol: tcp
      mode: host
    environment:
      - VERSION=${VERSION}
      - FIRST_BABY_TIME_CONFIG_FILE=${FIRST_BABY_TIME_CONFIG_FILE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ALIGO_API_KEY=${ALIGO_API_KEY}
      - ALIGO_ACCOUNT_ID=${ALIGO_ACCOUNT_ID}
      - ALIGO_SENDER=${ALIGO_SENDER}
      - JWT_KEY=${JWT_KEY}
      - CLOUD_MANAGEMENT_KEY=${CLOUD_MANAGEMENT_KEY}
      - S3_REGION=${S3_REGION}
      - AWS_S3_ID=${AWS_S3_ID}
      - AWS_S3_KEY=${AWS_S3_KEY}
      - S3_PROFILE_BUCKET=${S3_PROFILE_BUCKET}
    volumes:
      - /Users/yumyeongcheol/Desktop/mspring03/project/Server/config.yaml:/usr/share/first-baby-time/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
#networks:
#  dms-sms-local:
#    name: dms-sms-local
#    driver: overlay
