version: '3.5'
services:
  first-baby-time:
    image: jinhong0719/first-baby-time:${VERSION}.RELEASE
    container_name: first-baby-time
    networks:
      - dms-sms-local
    ports:
    - target: 8000
      published: 8000
      protocol: tcp
      mode: host
    environment:
      - VERSION=${VERSION}
      - CONFIG_FILE=${CONFIG_FILE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ALIGO_API_KEY=${ALIGO_API_KEY}
      - ALIGO_ACCOUNT_ID=${ALIGO_ACCOUNT_ID}
      - ALIGO_SENDER=${ALIGO_SENDER}
      - JWT_KEY=${JWT_KEY}
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=first-baby-time]

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
