version: '3.5'
services:
  server:
    image: mspring03/first-baby-time:${VERSION}.RELEASE
    container_name: server
    ports:
    - target: 8000
      published: 8000
      protocol: tcp
      mode: host
    environment:
      - VERSION=${VERSION}
      - FIRST_BABY_TIME_CONFIG_FILE=${FIRST_BABY_TIME_CONFIG_FILE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ALIGO_API_KEY=${ALIGO_API_KEY}
      - ALIGO_ACCOUNT_ID=${ALIGO_ACCOUNT_ID}
      - ALIGO_SENDER=${ALIGO_SENDER}
      - JWT_KEY=${JWT_KEY}
    volumes:
      - ./config.yaml:/usr/share/first-baby-time/config.yaml
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=first-baby-time]

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
