version: '3.5'
services:
  server:
    image: mspring03/first-baby-time:${VERSION}.RELEASE
    container_name: server
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    environment:
      - VERSION=${VERSION}
      - FIRST_BABY_TIME_CONFIG_FILE=${FIRST_BABY_TIME_CONFIG_FILE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ALIGO_API_KEY=${ALIGO_API_KEY}
      - ALIGO_ACCOUNT_ID=${ALIGO_ACCOUNT_ID}
      - ALIGO_SENDER=${ALIGO_SENDER}
      - JWT_KEY=${JWT_KEY}
      - CLOUD_MANAGEMENT_KEY=${CLOUD_MANAGEMENT_KEY}
    volumes:
      - /Users/yumyeongcheol/Desktop/mspring03/project/Server/config.yaml:/usr/share/first-baby-time/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
#  zookeeper:
#    image: debezium/zookeeper:1.2
#    ports:
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
#  kafka:
#    image: debezium/kafka:1.2
#    ports:
#      - 9092:9092
#    links:
#      - zookeeper
#    environment:
#      - ZOOKEEPER_CONNECT=zookeeper:2181
#  connect:
#    image: debezium/connect:1.4
#    ports:
#      - 8083:8083
#    links:
#      - zookeeper
#      - kafka
#    environment:
#      - BOOTSTRAP_SERVERS=kafka:9092
#      - GROUP_ID=1
#      - CONFIG_STORAGE_TOPIC=my_connect_configs
#      - OFFSET_STORAGE_TOPIC=my_connect_offsets
#      - STATUS_STORAGE_TOPIC=my_connect_statuses

